### PR TITLE
Replaced Deprecated Slack API request with newer API calls to resolve #24   

### LINKED ISSUE #24: Update to new Slack API calls
It seems the bot is pointing to the wrong im API call, and the new API call is `conversations`

### PR DESCRIPTION
**Pull request by yougaindra**
PR to resolve #24 
Changes:
1. updated deprecated slack api call(`https://slack.com/api/im.open`) with `https://slack.com/api/conversations.open`.
2. Fixed bug on line 75 which was setting dictionary data to None in case `UNFURL=False`  because dictionary.update returns None, and re-assignment is not required.
3. changed variable name to be more descriptive on line number 59 and 77
4. Minor README.md edits to reflect changes in bot.py

### CODE REVIEW

**Comment by yougaindra** [comment]
According to PyCharm there are some Auto-formatting changes as well, let me know if I should commit those as well.

**Comment by orliesaurus** [comment]
> According to PyCharm there are some Auto-formatting changes, let me know if I should commit those as well.

Yeah sure!

**Comment by orliesaurus** [comment]
make a new PR for those if you can 👍

**Comment by yougaindra** [comment]
@orliesaurus The auto-format changes are not too significant. you can review it([diff](https://github.com/orliesaurus/greetingslack/compare/master...yougaindra:master)) and let me know if I should create PR.

**Comment by andreasaez** [comment]
Is there anything we need to do on our end? I just got another email from Slack saying that im.open is still being affected.

**Comment by yougaindra** [comment]
@andreasaez I checked again, I did not find any usage of `im.open`, are you sure you have deployed the most recent source code?

**Pull request merged**
