### PR TITLE
Update bot.py

### PR DESCRIPTION
**Pull request by mdzidic**
Add suppress of InsecureRequestWarning

### CODE REVIEW

**Comment by orliesaurus** [comment]
Hey there @mdzidic I think it's an interesting pull request, however a warning is there for a reason, I understand this removes it for "cosmetic" reasons but do you think it should be kept for transparency purposes? I remember using this trick in other projects because I didn't want to see the message, but I am wondering if it makes sense merging it in and therefore "removing" the warning?
What do you think? Is it safe, considering there might be people using this bot for anything in Slack?

**Comment by mdzidic** [comment]
Hello @orliesaurus, as it's readable and commented enough I think it's safe to leave it there as it's only filling log file on every request.

**Comment by orliesaurus** [comment]
Thanks @mdzidic

**Comment by orliesaurus** [comment]
now let's dance :dancing_men:

**Pull request merged**
