### PR TITLE
Add support for the bot forwarding responses to a channel

### PR DESCRIPTION
**Pull request by nbkrause**
When the bot sends a DM to a new user, if that user responds to the bot the response would have been lost. Now, when a user responds to the bot, the bot forwards the message to a channel identified by the environment variable `RESPONSE_CHANNEL`. 

This functionality requires you generate an API token for the channel and store it in an environment variable `CHANNEL_TOKEN`.

### CODE REVIEW

**Comment by orliesaurus** [comment]
damn!

**Comment by orliesaurus** [comment]
@nbkrause  do you want me to update the readme.md file to add this information, or would you rather do it before I merge it in?!

**Comment by nbkrause** [comment]
@orliesaurus Sorry about that. Added a note to the documentation.

**Comment by orliesaurus** [comment]
Thank you @nbkrause I merged your changes in :)

**Pull request merged**
